# Generated by Django 4.0.3 on 2022-03-17 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('rent', 'RENT'), ('investment', 'INVESTMENT'), ('tax', 'TAX'), ('bill', 'BILL'), ('loan', 'LOAN'), ('shopping', 'SHOPPING'), ('lifestyle', 'LIFESTYLE'), ('food', 'FOOD'), ('other', 'OTHER')], max_length=20)),
                ('item', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('importance', models.BooleanField(default=False)),
            ],
        ),
    ]
