# Generated by Django 4.0.3 on 2022-03-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='importance',
            new_name='important',
        ),
    ]
