# Generated by Django 4.0.3 on 2022-03-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack', '0003_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
