# Generated by Django 4.0.3 on 2022-04-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack', '0008_alter_expense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDA',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exp_start_date', models.DateField()),
                ('exp_end_date', models.DateField()),
            ],
        ),
    ]
